export interface TablaViaticos {
    oficina: number,
    ejercicio: number,
    noViat: number,
    fecha: string, 
    noEmp: number,
    origenId: number, 
    destinoId: number, 
    motivo: string, 
    fechaSal: string, 
    fechaReg: string, 
    dias: number,
    inforFecha: string,
    inforAct: string,
    nota: string,
    estatus: number,
    fechaMod: string,
    pol: number,
    polMes: number,
    caja: number,
    cajaVale: number,
    cajaRepo: number,
    noEmpCrea: number,
    inforResul: string
}